# Generated by Django 3.1.6 on 2021-02-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('mobile', models.CharField(default='', max_length=70)),
                ('add1', models.CharField(default='', max_length=500)),
                ('add2', models.CharField(default='', max_length=500)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
