# Generated by Django 3.1.6 on 2021-02-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210213_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(default='', max_length=70),
        ),
    ]
